# Generated by Django 4.2.7 on 2024-01-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='name',
            field=models.CharField(default='led', max_length=50),
        ),
        migrations.AlterField(
            model_name='led',
            name='value',
            field=models.IntegerField(),
        ),
    ]
