# Generated by Django 4.2.7 on 2024-01-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0002_led_name_alter_led_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='name',
            field=models.CharField(default='led', max_length=50, unique=True),
        ),
    ]
