# Generated by Django 4.2.7 on 2024-01-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0003_alter_led_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='led',
            name='name',
        ),
        migrations.AlterField(
            model_name='led',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grow_guard.device'),
        ),
    ]
