# Generated by Django 4.2.7 on 2023-12-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0003_alter_device_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('name', 'device')},
        ),
    ]
