# Generated by Django 4.2.7 on 2023-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0004_alter_sensor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
