# Generated by Django 4.2.7 on 2023-12-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0005_alter_sensor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(auto_created='files/images', upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grow_guard.device')),
            ],
        ),
    ]
