# Generated by Django 4.2.7 on 2023-12-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0006_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.ImageField(upload_to='files/images'),
        ),
    ]
