# Generated by Django 4.2.7 on 2023-12-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0007_alter_camera_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='name',
        ),
    ]
