# Generated by Django 4.2.7 on 2023-12-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0009_alter_camera_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
