# Generated by Django 4.2.7 on 2023-12-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0010_alter_camera_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='device',
        ),
    ]
