# Generated by Django 4.2.7 on 2023-12-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0012_camera_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
