# Generated by Django 4.2.7 on 2023-12-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0013_sensor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
