# Generated by Django 4.2.7 on 2023-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0014_alter_temperature_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
