# Generated by Django 4.2.7 on 2023-12-20 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0015_alter_temperature_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighting',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightings', to='grow_guard.device'),
        ),
    ]
