# Generated by Django 4.2.7 on 2023-12-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0016_alter_lighting_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
