# Generated by Django 4.2.7 on 2023-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0017_delete_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
