# Generated by Django 4.2.7 on 2023-12-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grow_guard', '0018_camera_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='grow_guard.device'),
        ),
    ]
